[package]
name = "hashsplit"
version = "0.1.0"
authors = ["Cole Miller <m@cole-miller.net>"]
edition = "2018"

[features]
default = ["alloc"]
alloc = []
immutable-vector = ["im-rc"]

[dependencies]
either = "1.6.1"
im-rc = { version = "15.0.0", optional = true }
